[redis]
address = "172.17.0.6"
port = 6379
passWord = "doper"
db = 0

[etcd]
host = ["172.17.0.6:49166", "172.17.0.6:49168", "172.17.0.6:49170"]
basePath = "zuzuxia_srv"
serverPathLogic = "ZuLogicRpc"
timeout = 5

[jaeger]
scheme = "http://"
host = "172.17.0.6:14268"
path = "/api/traces"

[api]
listenPort = 7070